/**
 * 进行定义请求Action类型
 */
'use strict';

//首页
export const HOME_ACTION = 'HOME_ACTION';

//登录
export const PERFORM_LOGIN_ACTION = 'PERFORM_LOGIN_ACTION';
export const RECEIVE_LOGIN_ACTION = 'RECEIVE_LOGIN_ACTION';

//新闻资讯
export const PERFORM_NEWSlIST_ACTION = 'PERFORM_NEWSlIST_ACTION';
export const RECEIVE_NEWSlIST_ACTION = 'RECEIVE_NEWSlIST_ACTION';
export const GET_MORE_NEWSLIST_ACTION = 'GET_MORE_NEWSLIST_ACTION';
export const REFRESH_NEWSlIST_ACTION = 'REFRESH_NEWSlIST_ACTION';
export const HAS_FINISHED_ACTION = 'HAS_FINISHED_ACTION';
export const ERROR_NEWSLIST_ACTION = 'ERROR_NEWSLIST_ACTION';