# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '8.0'

target 'olive' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for olive

  pod 'RSKImageCropper'
  pod 'QBImagePickerController'
  # U-Share SDK UI模块（分享面板，建议添加）
  pod ‘UMengUShare/UI’
  # 集成微信
  pod ‘UMengUShare/Social/ReducedWeChat'
  # 集成QQ
  pod ‘UMengUShare/Social/ReducedQQ'
  # 集成微博
  pod ‘UMengUShare/Social/ReducedSina'


  target 'oliveTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'olive-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for olive-tvOS

  target 'olive-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
